{% set name = "pcdsutils" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d04d7c78251a8e78223a8b26614d940dc74c7c7e28be71df2ba91326e5945ddc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - requirements-from-conda = pcdsutils.requirements:_requirements_from_conda
    - requirements-compare = pcdsutils.requirements:_compare_requirements

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pypandoc
    - pyqt >=5
    - pyyaml
    - qtpy
    - qtpyinheritance
    - requests

test:
  imports:
    - pcdsutils
    - pcdsutils.qt
  requires:
    - pytest
    - pytest-qt

about:
  home: https://github.com/pcdshub/pcdsutils
  summary: SLAC National Accelerator Laboratory Photon Controls PCDS Python Utilities
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
