{% set name = "pcdsutils" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9b4067a461436f3b456064a65e50ab507f6319541869728cc708d789cc78b206

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - requirements-from-conda = pcdsutils.requirements:_requirements_from_conda
    - requirements-compare = pcdsutils.requirements:_compare_requirements

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - prettytable
    - pypandoc
    - pyqt >=5
    - pyyaml
    - qtpy
    - qtpyinheritance
    - requests

test:
  imports:
    - pcdsutils
    - pcdsutils.qt
  requires:
    - pytest
    - pytest-qt

about:
  home: https://github.com/pcdshub/pcdsutils
  summary: SLAC National Accelerator Laboratory Photon Controls PCDS Python Utilities
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
