{% set name = "pcdsutils" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 885932ebde4b09da5200849a0d225d32d522b45bbb070f463db9cb7e77daf647

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - requirements-from-conda = pcdsutils.requirements:_requirements_from_conda
    - requirements-compare = pcdsutils.requirements:_compare_requirements

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyqt >=5
    - qtpy
    - qtpyinheritance

test:
  imports:
    - pcdsutils
    - pcdsutils.qt
  requires:
    - pytest
    - pytest-qt

about:
  home: https://github.com/pcdshub/pcdsutils
  summary: 'SLAC National Accelerator Laboratory Photon Controls PCDS Python Utilities'
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
